### PR TITLE
chore(resource): update quotes and remove template strings

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Update quotes and remove template strings

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, update quotes and remove template strings

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
What's the reason for this change?

**Comment by Tony133** [comment]
Hi @kamilmysliwiec, I created this pull for this reason when I use the `nest g resource` command I get this(see screenshot): 

screenshot

it is not recognized as template strings in the `findAll` method.

I think you should put the quotes `''` since we don't pass parameters inside the string, so with this change we should have our file generated like this (see screenshot):

screenshot2


Tony

**Comment by kamilmysliwiec** [comment]
Using template literals (``) without passing arguments is fine https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by Tony133** [comment]
Usually when I have no parameters I use quotes `` '' `` and not template strings. anyway okay 👍

**Pull request closed without merging**
