### PR TITLE
feat: generate class with suffix

### PR DESCRIPTION
**Pull request by santoshyadav198613**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #123 

## What is the new behavior?

The classes with "." will be generated without "."

User.Entity will generate class user-entity.ts and class name as UserEntity

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Are you sure that this PR solves #123 issue? What if someone wants to generate `user.entity.ts` file which contains `UserEntity` class inside (a very common scenario in NestJS)

**Comment by santoshyadav198613** [comment]
> Are you sure that this PR solves #123 issue? What if someone wants to generate `user.entity.ts` file which contains `UserEntity` class inside (a very common scenario in NestJS)

Ok will take care of file name as well. This resolves the ClassName issue.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec ,

One solution which I am thinking about is, adding one parameter as className which will be used internally so whatever changes we do to className will not impact file name.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec ,
Done ready for review now, the checks are in place and added the test case, all tests are green.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec ,
Please review once you are free.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec ,

Did you got the chance to review, please let me know if any changes are needed.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec , @MarkPieszak ,
Can you review this one, please let me know if any changes are needed.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec ,
Let me know if we need this PR.

**Comment by kamilmysliwiec** [comment]
I'll review it as long as I find some spare time

**Comment by santoshyadav198613** [comment]
> I'll review it as long as I find some spare time

Thanks a lot for your response 🙂

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
