### PR TITLE
fixing bug length of null

### PR DESCRIPTION
**Pull request by minehp**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
I'm looking at the source code and I don't understand how this change is supposed to help us(?)

**Comment by minehp** [comment]
I have the problem while generate controller schema with command `nest g controller login`. i am tracing the code and there is a problem with file metadata.manager.ts line 139, there is regex test and result checked as array (`matches.length`). regex test result null if the test failed not array with 0 length.

i am sorry my english language is bad. i tried to explain it as clear as i can.

**Comment by kamilmysliwiec** [comment]
Shouldn't we just change this:
```typescript
if (matches.length > 0) {
```
to this:
```typescript
if (matches && matches.length > 0) {
```
?

**Comment by minehp** [comment]
show me how regex can return empty array...? the code line 137 try to find carriage return and whitespace character (`const matches = text.match(/^\r?\n\s*/);`). i never knew if regex match function return empty array.

you can use this

```javascript
if (matches) {
```

or like my changes

```javascript
if (text.match(/^\r?\n\s*/)) {
```

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
