### PR TITLE
feat(resource): cqrs schematics

### PR DESCRIPTION
**Pull request by TripShade**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently ```nest g resource``` generates resources for a variety of design patterns.

Issue Number: N/A

## What is the new behavior?
When running ```nest g resource``` a new option exists ```CQRS (Command Query Responsibility Segregation) REST API + Bull```. The new options generates resources based on the current [CQRS documentation](https://docs.nestjs.com/recipes/cqrs). [Bull](https://docs.nestjs.com/techniques/queues) Queues have been added between command-handlers and services, to delay writes/work done by services.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
```CQRS (Command Query Responsibility Segregation) REST API + Bull``` im sure there is a better name for the dialog option somewhere out there.

### CODE REVIEW

**Comment by TripShade** [comment]
Ah damn still some failed tests for deep matched resources. I'll get to those soon.

**Comment by micalevisk** [comment]
can't we leave Bull out of this?

**Comment by TripShade** [comment]
@micalevisk Possibly however if you are using CQRS you might end up moving writes or heavy work behind a queue anyway. At that point it’s very nice to not have to write x amount of import statements.

**Comment by TripShade** [comment]
```Service Factory › should manage declaration in foo module``` unit test fails can’t figure out why. Could it be end-of-line related? Im on MacOS. I havent touched any /service schematics.

**Comment by TripShade** [comment]
> `Service Factory › should manage declaration in foo module` unit test fails can’t figure out why. Could it be end-of-line related? Im on MacOS. I havent touched any /service schematics.

NVM found it.

**Comment by TripShade** [comment]
Test have been added

**Comment by TripShade** [comment]
Can someone review this or give pointers as to what needs more attention?

**Comment by kamilmysliwiec** [comment]
Thanks for your contribution @TripShade!

However, there are no plans to add more schematics to the official collection. You can release your own CQRS schematic as an open-source, community-driven NPM package.

**Pull request closed without merging**
