### PR TITLE
feat: allow easier deployment with default app schematics

### PR DESCRIPTION
**Pull request by sinedied**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, the generated starter app has 2 issues:
- It use a hardcoded port (3000) instead of using `process.env.PORT` with a fallback
- It does not allow to package the app properly using `npm pack`

Both these issues cause the default generated app to be undeployable on most cloud providers.

Issue Number: N/A

## What is the new behavior?

This PR fixes the 2 issues above, so the default generated app can be deployed easily on most cloud providers.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by sinedied** [comment]
Just saw that a similar PR was sent (currently in conflict), without the packaging part: https://github.com/nestjs/schematics/pull/288

**Comment by jdubois** [comment]
This would definitely improve deployment on Azure 🎉

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/schematics/pull/288

**Comment by sinedied** [comment]
@kamilmysliwiec as #288 seems stalled, and this one also adds proper packaging would it be ok if I add @BrunnerLivio as co-author on this PR to give him credits and re-open this one?

**Comment by BrunnerLivio** [comment]
@sinedied I think it makes sense to go with your PR instead! No worries about credits :)

**Review by micalevisk — COMMENTED** [review]
this LGTM!

@kamilmysliwiec can you please close #288 and review this one instead?

**Comment by kamilmysliwiec** [comment]
This has been discussed in the past and currently, we don't plan on making `PORT` the default. I left 1 PR open just in case we change our mind in the future.

**Comment by sinedied** [comment]
Hi @kamilmysliwiec, would it be possible to share a link to the discussion about not using `process.env.PORT`? I don't recall having seen one on this repo, and I would like to understand why you don't want this as a default.
The only reference I found is [the issue about it](https://github.com/nestjs/schematics/issues/125) on this repo, but you stated there that it should be made the default so I'm a bit confused: https://github.com/nestjs/schematics/issues/125#issuecomment-468786272
Thanks

**Pull request closed without merging**
