### PR TITLE
Init new nest project with nest v5 instead of nest v5 beta.6

### LINKED ISSUE #49: Nest new command initialises a project with beta version of nestjs 5
when executing `nest new` command, the cli inits the project with beta 6 of nest v5, the schematics for ts are not updated.

### PR DESCRIPTION
**Pull request by avatsaev**
closes #49

### CODE REVIEW

**Comment by ThomRick** [comment]
Hi @avatsaev 
Thanks for your PR but can't merge without signed commits
Please use the GutHub instructions to do it ;-)

**Comment by avatsaev** [comment]
on it

**Comment by avatsaev** [comment]
Hey @ThomRick I'm about to force push a signed commit, I see you already merge, do I push anyway?

**Comment by ThomRick** [comment]
Hey @avatsaev 
Yup I changed the base branch and the merge button was unlocked
So I don't waste of time I clicked on it 😛 

Thanks for your PR by the way !
Don't forget to get your GPG key to simplify your contribution integration and being in the present of software development ❤️

**Comment by avatsaev** [comment]
Thanks, yes I've setup my workstation to sign all commits by default from now own.
Very nice work on the angular schematics by the way, this thing is powerful, but not easy to grasp.

**Comment by ThomRick** [comment]
Thanks ! 😄 
Yeah a little bit difficult to start to develop with but when it's set up it's very powerful.

I'm trying to integrate it in my current position to scaffold all project templates.

**Pull request merged**
